### ISSUE TITLE
java.lang.IncompatibleClassChangeError when MoreThanOneElementException is thrown

### ISSUE THREAD

**Issue by dnahodil** [dnahodil/groovy-extra-list-behaviour#20]
**Steps to reproduce**
Call only() on a list with more than one element. e.g.:

``` groovy
[1, 2].only()
```

**What should happen**
A MoreThenOneElementException is thrown.

**What does happen**
The following error is thrown:

```
java.lang.IncompatibleClassChangeError: the number of constructors during runtime and compile time for java.lang.RuntimeException do not match. Expected -1 but got 5
    at com.dnahodil.groovy.extensions.MoreThanOneElementException.<init>(MoreThanOneElementException.groovy:6)
    at com.dnahodil.groovy.extensions.ListExtensions.only(ListExtensions.groovy:13)
```

**Comment by dnahodil** [comment]
Looks like this is only a problem on some versions of Java.

Ref: http://blog.proxerd.pl/article/how-to-fix-incompatibleclasschangeerror-for-your-groovy-projects-running-on-jdk7

**Comment by dnahodil** [comment]
On second look it seems to work fine on Groovy 2.2.1 but is broken on 2.0.5.
